[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
prereqs_program_solana = "WBA52hW35HZU5R2swG57oehbN2fTr7nNhNDgfjnqUoZ"

[programs.devnet]
prereqs_program_solana = "WBA52hW35HZU5R2swG57oehbN2fTr7nNhNDgfjnqUoZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/leo/.config/solana/mainnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
